apiVersion: v1
kind: Service
metadata:
  name: mrbs-mysql
  labels:
    app: mrbs
spec:
  ports:
    - port: 3306
  selector:
    app: mrbs
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mrbs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrbs-mysql
  labels:
    app: mrbs
spec:
  selector:
    matchLabels:
      app: mrbs
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mrbs
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db-root
              key: password
        - name: MYSQL_DATABASE
          value: "mrbs"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-db-auth
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db-auth
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
